version: '3'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./root.cert:/root_ca.crt:ro
      #- $PWD/site:/srv
      - caddy_data:/data:rw
      - caddy_config:/config:rw
    ports:
      - 80:80
      - 443:443
    networks:
      - gitea_web_net
      - drone_web_net
  gitea:
    container_name: gitea
    image: docker-linux.nexus.lcl.leven.dev/infra/gitea:latest
    restart: unless-stopped
    ports:
      - 200:200
    volumes:
      - gitea_data:/data:rw
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_PORT=200
      - SSH_LISTEN_PORT=200
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_db
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${POSTGRES_PASS}
    depends_on:
      - gitea_db
    networks:
      - gitea_db_net
      - gitea_web_net
  gitea_db:
    image: postgres:latest
    container_name: gitea_db
    restart: unless-stopped
    volumes:
      - gitea_db_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    networks:
      - gitea_db_net
  drone:
    container_name: drone
    image: docker-linux.nexus.lcl.leven.dev/infra/drone:latest
    restart: unless-stopped
    volumes:
      - drone_data:/data:rw
    environment:
      - DRONE_GITEA_CLIENT_ID=${GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${GITEA_CLIENT_SECRET}
      - DRONE_GITEA_SERVER=https://gitea.leven.dev
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_RPC_SECRET=${DRONE_SECRET}
      - DRONE_DATADOG_ENABLED=false
      - DRONE_SERVER_PROTO=https
      - DRONE_SERVER_HOST=drone.leven.dev
      - DRONE_USER_CREATE=username:adminuser,admin:true
    networks:
      - drone_web_net

volumes:
  drone_data:
    external: true
  gitea_db_data:
    external: true
  gitea_data:
    external: true
  caddy_data:
    external: true
  caddy_config:

networks:
  drone_web_net: null
  gitea_db_net: null
  gitea_web_net: null
